In [2]:
import numpy as np

A = np.zeros(shape=(3,2))
mu, sigma = 0, 0.1 # mean and standard deviation
for i in range(A.shape[0]):
    for j in range(A.shape[1]):
        A[i][j] = np.random.normal(mu, sigma, 1)
print("Matrix A:")
print(A)
print("Rank of Matrix A: ", np.linalg.matrix_rank(A))

Matrix A:
[[ 0.01159693 -0.03711848]
 [-0.15974645 -0.01829756]
 [-0.03816238 -0.11590198]]
Rank of Matrix A:  2


In [3]:
N = 500
v = np.zeros(shape=(2,1))
X = np.zeros(shape=(3,N))
x = np.zeros(shape=(3,1))
for i in range(N):
    v[0] = np.random.normal(mu, sigma, 1)
    v[1] = np.random.normal(mu, sigma, 1)
    x = np.matmul(A, v)
    X[0][i] = x[0]
    X[1][i] = x[1]
    X[2][i] = x[2]
print("Shape of Matrix X: ", X.shape)
print("Rank of Matrix X: ", np.linalg.matrix_rank(X))

Shape of Matrix X:  (3, 500)
Rank of Matrix X:  2


In [17]:
u, s, vT = np.linalg.svd(X)
print("Matrix s")
print(s)
# print("Matrix s")
# print(s.shape)
# print("Matrix vT")
# print(vT.shape)
XXT = np.matmul(X, X.transpose())
w, v = np.linalg.eig(XXT)
print("Matrix v")
print(w)

Matrix s
[  3.89583368e-01   2.48009255e-01   4.32091129e-17]
Matrix v
[  6.93889390e-18   6.15085903e-02   1.51775200e-01]
